version: '3.8'

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
        - project_network

  app:
    build: .
    container_name: app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ~/.aws:/root/.aws
    networks:
      - project_network


networks:
  project_network:
    driver: bridge
