name: Deploy on AWS

on: 
  push:
    branches:
     - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: ssh-pipeline
        uses: cross-the-world/ssh-pipeline@v1.2.0
        with:
          host: ${{ secrets.PUBLICIP }}
          user: ec2-user
          key: ${{ secrets.LABSUSERPEM }}
          script: |
            cd /Sydney-Riley-Project
            ./redeployAWS.sh
