name: Run Maven Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Install & Start Redis
      run: |
        sudo apt-get update
        sudo apt-get install -y redis-server
        redis-server --daemonize yes
        for i in {1..5}; do
          redis-cli ping && break
          echo "Waiting for Redis..."
          sleep 2
        done

    - name: Run Maven Tests
      run: mvn test

    - name: Print Failing Tests (if any)
      if: failure()
      run: cat target/surefire-reports/*.txt || true

    - name: Build Project
      run: mvn package

    - name: Deploy to Remote Server
      if: success()
      env:
        SSH_PRIVATE_KEY: ${{ secrets.LABSUSER_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
      run: |
        echo "$SSH_PRIVATE_KEY" > labsuser.pem
        chmod 600 labsuser.pem
        scp -i labsuser.pem target/dbot-1.0-SNAPSHOT-jar-with-dependencies.jar $REMOTE_USER@$REMOTE_HOST:/app/dbot.jar
        ssh -i labsuser.pem $REMOTE_USER@$REMOTE_HOST 'systemctl restart dbot'
